services:
  kogi-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kogi-app
    ports:
      - "127.0.0.1:8866:8866"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
